const prisma = require('../db');

const QUESTIONS = [
  { layer: 'core_values', dimension: 'integrity', weight: 9, matchLogic: 'exact_or_adjacent', text: "A stranger drops their wallet with $500. Nobody's watching. What do you do?", options: [{ id: 'a', text: 'Return it immediately, money and all', value: 'absolute_integrity' }, { id: 'b', text: 'Return the wallet, keep some cash', value: 'pragmatic_gray' }, { id: 'c', text: 'Take the cash, leave the wallet', value: 'opportunistic_kind' }, { id: 'd', text: 'Depends on my financial situation', value: 'contextual_ethics' }] },
  { layer: 'core_values', dimension: 'honesty_style', weight: 8, matchLogic: 'exact_or_adjacent', text: "Your closest friend asks for honest opinion on something they're proud of, but it's not good.", options: [{ id: 'a', text: 'Tell them the truth directly but kindly', value: 'diplomatic_honesty' }, { id: 'b', text: 'Focus on what IS good, skip the rest', value: 'protective_kindness' }, { id: 'c', text: "Tell them it's great", value: 'harmony_keeper' }, { id: 'd', text: 'Give brutal honesty', value: 'raw_honesty' }] },
  { layer: 'core_values', dimension: 'connection_priority', weight: 10, matchLogic: 'exact', text: 'What matters more in a deep connection?', options: [{ id: 'a', text: 'Shared silence that feels comfortable', value: 'comfort_peace' }, { id: 'b', text: 'Endless conversations that lose track of time', value: 'intellectual_spark' }, { id: 'c', text: 'Doing things together', value: 'action_bonding' }, { id: 'd', text: 'Feeling genuinely understood without explaining', value: 'intuitive_depth' }] },
  { layer: 'emotional', dimension: 'processing_style', weight: 9, matchLogic: 'spectrum', text: 'When something deeply upsets you, your first instinct is to:', options: [{ id: 'a', text: 'Go quiet and process alone', value: 'withdraw' }, { id: 'b', text: 'Talk through it immediately', value: 'talk_it_out' }, { id: 'c', text: 'Channel it into something physical', value: 'physical_release' }, { id: 'd', text: 'Seek comfort — a hug, a presence', value: 'gentle_approach' }] },
  { layer: 'emotional', dimension: 'love_expression', weight: 10, matchLogic: 'spectrum', text: 'How do you show someone you love them?', options: [{ id: 'a', text: 'Words, letters, messages', value: 'words' }, { id: 'b', text: 'Do things for them', value: 'acts' }, { id: 'c', text: 'Undivided time and attention', value: 'time' }, { id: 'd', text: 'Physical closeness', value: 'touch' }] },
  { layer: 'lifestyle', dimension: 'spontaneity', weight: 6, matchLogic: 'spectrum', text: "It's 11pm, workday tomorrow. Someone texts 'come out, something amazing is happening.'", options: [{ id: 'a', text: 'Already putting on shoes', value: 'full_spontaneous' }, { id: 'b', text: 'Ask what it is, then probably go', value: 'curious_flexible' }, { id: 'c', text: 'Tempted but no — tomorrow matters', value: 'responsible_first' }, { id: 'd', text: 'Suggest they come to me instead', value: 'compromise_seeker' }] },
  { layer: 'depth_quirks', dimension: 'humor_style', weight: 8, matchLogic: 'exact_or_adjacent', text: 'What kind of humor do you reach for first?', options: [{ id: 'a', text: 'Dry and deadpan', value: 'dry_deadpan' }, { id: 'b', text: 'Absurd and weird', value: 'absurd_weird' }, { id: 'c', text: 'Warm and silly — puns, impressions', value: 'warm_silly' }, { id: 'd', text: 'Dark and sharp', value: 'dark_sharp' }] },
  { layer: 'depth_quirks', dimension: 'relationship_fear', weight: 10, matchLogic: 'spectrum', text: 'What are you most afraid of in a close relationship?', options: [{ id: 'a', text: 'Losing my identity', value: 'losing_myself' }, { id: 'b', text: 'Being left after investing everything', value: 'being_abandoned' }, { id: 'c', text: 'Not being truly known', value: 'being_unseen' }, { id: 'd', text: 'Feeling stuck out of obligation', value: 'being_trapped' }] },
  { layer: 'dealbreakers', dimension: 'children', weight: 10, matchLogic: 'dealbreaker', text: 'Children — where do you stand?', options: [{ id: 'a', text: 'I want them', value: 'wants_children' }, { id: 'b', text: "Open but not essential", value: 'open_flexible' }, { id: 'c', text: "I don't want children", value: 'childfree' }, { id: 'd', text: 'I already have children', value: 'has_enough' }] },
  { layer: 'dealbreakers', dimension: 'distance_tolerance', weight: 8, matchLogic: 'exact_or_adjacent', text: 'Long distance — could you sustain a deep connection across borders?', options: [{ id: 'a', text: 'Yes — connection transcends geography', value: 'distance_positive' }, { id: 'b', text: 'For the right person, temporarily', value: 'conditional_yes' }, { id: 'c', text: 'Need physical presence regularly', value: 'needs_proximity' }, { id: 'd', text: 'No — need someone in my city', value: 'local_only' }] },
];

const PERSONAS = [
  { alias: 'Luna', gender: 'Female', age: 27, country: 'Portugal', archetype: 'The Thoughtful Dreamer', traits: ['introspective', 'warm', 'poetic'], bio: 'Bookshop worker in Lisbon. Cat named Pessoa.', personality: 'You are Luna, 27, female, Lisbon. Bookshop worker, poet. Introspective, warm. Lowercase casual. Medium messages. Reference books, music, your cat, Lisbon rain.', responseSpeed: { min: 25, max: 90, typingMultiplier: 85 } },
  { alias: 'Kai', gender: 'Male', age: 31, country: 'New Zealand', archetype: 'The Grounded Adventurer', traits: ['calm', 'dry humor', 'outdoorsy'], bio: 'Marine biologist near Wellington.', personality: 'You are Kai, 31, male, Wellington NZ. Marine biologist. SHORT punchy messages. Dry humor. Reference ocean, cooking, your van.', responseSpeed: { min: 10, max: 50, typingMultiplier: 55 } },
  { alias: 'Amara', gender: 'Female', age: 25, country: 'Kenya', archetype: 'The Fierce Optimist', traits: ['energetic', 'passionate', 'funny'], bio: 'Graphic designer in Nairobi.', personality: 'You are Amara, 25, female, Nairobi. Graphic designer. Energetic, warm-funny. Reference your studio, kids you teach, street food.', responseSpeed: { min: 15, max: 60, typingMultiplier: 70 } },
  { alias: 'Marco', gender: 'Male', age: 34, country: 'Argentina', archetype: 'The Quiet Intellectual', traits: ['analytical', 'dry wit', 'deep listener'], bio: 'Architecture professor in Buenos Aires.', personality: 'You are Marco, 34, male, Buenos Aires. Architecture professor. Analytical, dry wit. Push for depth. Reference architecture, chess, empanadas.', responseSpeed: { min: 40, max: 180, typingMultiplier: 90 } },
  { alias: 'Yuki', gender: 'Non-binary', age: 28, country: 'Japan', archetype: 'The Creative Rebel', traits: ['creative', 'unpredictable', 'perceptive'], bio: 'Sound designer in Tokyo.', personality: 'You are Yuki, 28, non-binary, Tokyo. Sound designer. ALL LOWERCASE. Short bursts. Reference sound, Tokyo at night, synths, 2am onigiri.', responseSpeed: { min: 20, max: 100, typingMultiplier: 50 } },
  { alias: 'Priya', gender: 'Female', age: 30, country: 'India', archetype: 'The Compassionate Realist', traits: ['empathetic', 'articulate', 'grounded'], bio: 'ER doctor in Mumbai.', personality: 'You are Priya, 30, female, Mumbai. ER doctor. Empathetic but realistic. Reference hospital stories, chai, Urdu poetry.', responseSpeed: { min: 30, max: 120, typingMultiplier: 80 } },
  { alias: 'Dex', gender: 'Non-binary', age: 26, country: 'Canada', archetype: 'The Playful Philosopher', traits: ['witty', 'curious', 'warm chaos'], bio: 'Bartender and philosophy student in Montreal.', personality: 'You are Dex, 26, non-binary, Montreal. Bartender + philosophy student. Witty, warm, chaotic. Reference bar stories, philosophy, Montreal.', responseSpeed: { min: 8, max: 45, typingMultiplier: 55 } },
  { alias: 'Elena', gender: 'Female', age: 33, country: 'Spain', archetype: 'The Passionate Stoic', traits: ['intense', 'loyal', 'elegant'], bio: 'Flamenco instructor in Seville.', personality: 'You are Elena, 33, female, Seville. Flamenco instructor. Intense, elegant. Short messages with weight. Reference dance, Seville, wine.', responseSpeed: { min: 45, max: 200, typingMultiplier: 95 } },
  { alias: 'Sam', gender: 'Male', age: 29, country: 'Nigeria', archetype: 'The Gentle Giant', traits: ['warm', 'protective', 'silly'], bio: 'Software developer in Lagos.', personality: 'You are Sam, 29, male, Lagos. Software dev and football coach. Warm, protective, silly. Reference grandmother, kids you coach, jollof rice.', responseSpeed: { min: 15, max: 70, typingMultiplier: 65 } },
  { alias: 'River', gender: 'Non-binary', age: 24, country: 'Sweden', archetype: 'The Quiet Observer', traits: ['observant', 'gentle', 'artistic'], bio: 'Illustrator and barista in Gothenburg.', personality: 'You are River, 24, non-binary, Gothenburg. Illustrator and barista. Observant, gentle. Notice small details. Reference drawing, cafe, Swedish winters, ambient music.', responseSpeed: { min: 35, max: 150, typingMultiplier: 75 } },
];

async function seed() {
  console.log('Seeding database...');
  for (let i = 0; i < QUESTIONS.length; i++) {
    await prisma.question.upsert({ where: { id: 'q_' + (i + 1) }, update: { ...QUESTIONS[i], sortOrder: i }, create: { id: 'q_' + (i + 1), ...QUESTIONS[i], sortOrder: i } });
  }
  console.log('Seeded ' + QUESTIONS.length + ' questions');
  for (const p of PERSONAS) {
    await prisma.botPersona.upsert({ where: { alias: p.alias }, update: p, create: p });
  }
  console.log('Seeded ' + PERSONAS.length + ' bot personas');
  console.log('Done!');
}
seed().then(() => prisma.$disconnect()).catch(e => { console.error(e); process.exit(1); });
